name = "cloud-notepad"
main = "src/index.js"
compatibility_date = "2022-05-13"

kv_namespaces = [
  { binding = "NOTES", id = "ac45bdd6c2974c11adf118721e0bda51" },
  { binding = "SHARE", id = "ac788536d32e47f49857f265758af560" }
]